# Generated by Django 4.1.4 on 2022-12-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
